name: Python types validation and JS compiler checks

on: 
  [pull_request]

jobs:
  python-types-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout pull request code
        uses: actions/checkout@v4

      - name: Use Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy
      
      - name: Validating the Python code with mypy
        run: mypy $(git ls-files '*.py')
        